widgets:
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        type: recent_posts
        position: left
    -
        type: categories
        position: left
    -
        type: tags
        position: left